# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=50)),
                ('play_style', models.TextField()),
            ],
        ),
    ]
